### ISSUE TITLE
翻译结果框内没有内容

### ISSUE THREAD

**Issue by cclibra** [elliottzheng/CopyTranslator#1]
您好：
软件使用中翻译源框Source会有内容，但结果框Result中一直都是空白，网络没有问题，浏览器谷歌翻译也能打开。已升级到最新版本v0.0.5.2，请问如何解决

**Comment by elliottzheng** [comment]
您好，今天我也遇到了这个问题，可能是我使用的googletrans库出了问题，我今天会找时间看下。多谢反馈。

--------------原始邮件--------------
发件人："cclibra "<notifications@github.com>;
发送时间：2018年9月21日(星期五) 上午10:44
收件人："elliottzheng/CopyTranslator" <CopyTranslator@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[elliottzheng/CopyTranslator] 翻译结果框内没有内容 (#1)
-----------------------------------

 
您好：
 软件使用中翻译源框Source会有内容，但结果框Result中一直都是空白，网络没有问题，浏览器谷歌翻译也能打开。已升级到最新版本v0.0.5.2

**Comment by elliottzheng** [comment]
@cclibra 您好，问题已经在0.0.5.3修复，请下载最新版本重新安装。如仍有问题可以重开此issue

**Comment by SherryGIS** [comment]
您好 遇到了和楼上一样的问题，联网状态，下载了CopyTranslator_v0.0.7-Kylin-RC1版本，原文框可以自动获取复制文字但是译文框没有出现翻译结果，点击翻译按钮也没有用。同学用的都可以，不知道是怎么回事？跟电脑的什么环境有关系吗？

**Comment by elliottzheng** [comment]
@SherryGIS 请查看 #29

**Comment by bh907** [comment]
你好，我这边网络没有问题，安装的是0.0.8版本，一开始可以翻译，但是因为没有关闭复制了几张图片，软件卡死，关闭后重启以后一直用不了，监视剪贴板没反应，直接复制黏贴翻译也不行，换了翻译网站也不行。配置文件也删除，重新安装依然没用。请问有什么解决方法？
