### ISSUE TITLE
内容字体大小

### ISSUE THREAD

**Issue by ToTheEdge** [elliottzheng/CopyTranslator#10]
**希望能自由调整内容的字体大小**

1. 专注模式目前可以调整字体大小（Ctrl+滚轮），但每次新翻译一段话，字体大小又还原了，没有记忆下来。
2. 对照模式目前尚不能调整字体大小。

**系统环境：**
 - CopyTranslator版本：v0.0.7 x86 版
 - 出现问题时的模式：MainMode/ FocusMode
 - 操作系统：win10 64位
 - 阅读器：Mendeley

**Comment by elliottzheng** [comment]
对照模式字体大小下个v0.0.8会加上。专注模式调整字体大小不是通过ctrl+滚轮来实现的，ctrl+滚轮暂时只能实现临时的字体调整，正确方法如下图，后续可能会用ctrl+滚轮来实现（其实昨天我刚发现了ctrl+滚轮能调，但是我暂时没办法响应这个ctrl+滚轮这个事件，这是文本框自己处理的）更多功能请查阅使用指南。
**CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能。**
![image](https://user-images.githubusercontent.com/22427645/49142731-76b19a80-f334-11e8-89ec-254dc1906750.png)

**Comment by ToTheEdge** [comment]
感谢你的回复！
