### ISSUE TITLE
增量复制模式下的清空问题

### ISSUE THREAD

**Issue by ToTheEdge** [elliottzheng/CopyTranslator#11]
**在专注模式下的增量复制：一阶段的翻译完成后，想进入下一阶段，右键——清空后，只是清空了当前的显示，重新复制后，依然会判定为增量复制，继续连着上一阶段的文本一同翻译。**（对照模式下亦是如此）

目前解决办法，重新关开增量复制一次。
希望能加入热键或者右键功能菜单，重置增量复制。

**系统环境：**
 - CopyTranslator版本：v0.0.7 x86 版
 - 出现问题时的模式：MainMode/ FocusMode
 - 操作系统：如win10 64位
 - 阅读器：Mendeley

**Comment by elliottzheng** [comment]
确实是个问题，感谢反馈，这是个bug，已经定位并解决了，下个构建版本会更新右键清空会重置增量复制。
