### ISSUE TITLE
API 又换了？？

### ISSUE THREAD

**Issue by hqyyqh** [elliottzheng/CopyTranslator#13]
又翻译不出来了/(ㄒoㄒ)/~~

**Comment by hqyyqh** [comment]
更新搞定了。确认了谷歌是在整你 ε=( o｀ω′)ノ

**Comment by elliottzheng** [comment]
大哥，配合一下，麻烦提issue的时候用模板。不然你看我们现在交流的效率就很低。我不知道你说的是哪个版本，因为我现在用v0.0.7 Kylin RC1用得好好的，我不知道你是不是用这个版本，你有没有更新，你用的什么系统，我啥也不知道，得全部重新问一遍，一问一答的效率很低。v0.0.7 Kylin RC1是昨天中午刚更新的，之前的版本全都不能用了。

**Comment by hqyyqh** [comment]
大佬我错了，以后我一定使用模板提 issue。
