### ISSUE TITLE
在双屏显示时，对照模式窗口漂移

### ISSUE THREAD

**Issue by ToTheEdge** [elliottzheng/CopyTranslator#14]
**在双屏显示时，对照模式窗口漂移**

主屏幕分辨率1366**768，附屏幕分辨率1920*1080，以底边对齐。飘移的具体规律：当对照窗口在附屏幕上超过主屏幕的高度时（768（凭肉眼观看）），点下其他程序，再回到CT，CT窗口就会下移至窗口顶端不高于768的位置（如图）。
（不知道这个位置是巧合，还是真跟两个屏幕分辨率有关系，但问题是100%能复现）

![window position issue](https://user-images.githubusercontent.com/19242810/49423507-b06e1f80-f7d2-11e8-8144-c8a6c51dfa4e.jpg)

**系统环境：**
 - CopyTranslator版本：v0.0.7-Kylin-RC1
 - 出现问题时的模式：FocusMode
 - 操作系统：如win10 64位
 - 阅读器：与阅读器无关

**Comment by elliottzheng** [comment]
感谢反馈，我晚些时候会测试下，可能的话下个版本修复。

**Comment by 123wuyu** [comment]
此问题有可能是win10对高分屏的支持问题

发件人: ToTheEdge <notifications@github.com>
发送时间: 2018年12月4日 14:42
收件人: elliottzheng/CopyTranslator <CopyTranslator@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [elliottzheng/CopyTranslator] 在双屏显示时，对照模式窗口漂移 (#14)


在双屏显示时，对照模式窗口漂移

主屏幕分辨率1366**768，附屏幕分辨率1920*1080，以底边对齐。飘移的具体规律：当对照窗口在附屏幕上超过主屏幕的高度时（768（凭肉眼观看）），点下其他程序，再回到CT，CT窗口就会下移至窗口顶端不高于768的位置（如图）。
（不知道这个位置是巧合，还是真跟两个屏幕分辨率有关系，但问题是100%能复现）

[window position issue]<https://user-images.githubusercontent.com/19242810/49423507-b06e1f80-f7d2-11e8-8144-c8a6c51dfa4e.jpg>

系统环境：

  *   CopyTranslator版本：v0.0.7-Kylin-RC1
  *   出现问题时的模式：FocusMode
  *   操作系统：如win10 64位
  *   阅读器：与阅读器无关

**Comment by elliottzheng** [comment]
短时间内没有这样的设备条件，无法测试，设备的分辨率都还蛮统一的。
我猜测可能是程序在副屏幕获取的窗口位置不对

**Comment by elliottzheng** [comment]
下一个版本重新构建后如果仍有此现象可以重新打开
