### ISSUE TITLE
适配高DPI及自动置顶。。。

### ISSUE THREAD

**Issue by i5151** [elliottzheng/CopyTranslator#15]
1、适配高DPI。
2、选择“始终置顶”有时会感到翻译窗口碍事，这时如果复制文本，翻译窗口最好自动置顶显示结果。

**Comment by elliottzheng** [comment]
1. 请问在高dpi下会发生什么，我这边没有测试环境，不太清楚发生什么问题，可以详细描述下吗
2. 自动置顶会加入下一步计划

**Comment by i5151** [comment]
![F3YIsA.png](https://s1.ax1x.com/2018/12/07/F3YIsA.png)
给你截张图，有适配和没适配的。
没适配高DPI的字是发虚的，看着眼睛会很不舒服，尤其是在看惯了适配之后的界面再看没适配的，对比会更强烈。
如果拿实际的例子对比：没有适配高DPI的显示效果就像看街头的小报，而适配高DPI的效果就像是印在铜版纸上的杂志。

**Comment by elliottzheng** [comment]
了解了，我会去研究下

**Comment by roison** [comment]
@i5151 高分屏的话，直接开启Win10的HIDPI兼容即可；适配的还不错。右键点击（或者快捷方式），“属性”→“兼容性”→“更改高DPI设置”，在“替代高DPI缩放设置”上打钩确定就可以了。 @elliottzheng 少侠可以把这个写在说明里。

**Comment by i5151** [comment]
> @i5151 高分屏的话，直接开启Win10的HIDPI兼容即可；适配的还不错。右键点击（或者快捷方式），“属性”→“兼容性”→“更改高DPI设置”，在“替代高DPI缩放设置”上打钩确定就可以了。 @elliottzheng 少侠可以把这个写在说明里。

这个从用高分屏之前就知道，效果比原生支持差太多了。

适配高分屏这么难吗？至于用这种方式偷懒？

**Comment by i5151** [comment]
如果微软解决好的话，就没有软件会特意适配高分屏了。

**Comment by elliottzheng** [comment]
高分屏适配这个问题，使用wxpython实现似乎没有找到相关的资料，但是因为下一个版本会使用Electron实现，整个应用相当于一个浏览器，应该能够得到解决。

**Comment by roison** [comment]
> > @i5151 高分屏的话，直接开启Win10的HIDPI兼容即可；适配的还不错。右键点击（或者快捷方式），“属性”→“兼容性”→“更改高DPI设置”，在“替代高DPI缩放设置”上打钩确定就可以了。 @elliottzheng 少侠可以把这个写在说明里。
> 
> 这个从用高分屏之前就知道，效果比原生支持差太多了。
> 
> 适配高分屏这么难吗？至于用这种方式偷懒？

当然很麻烦啊，连网易云音乐和Foxmail都是去年才适配高分屏的，像百度网盘到现在都没适配高分屏；这还是BAT，何况个人开发者啊。

**Comment by i5151** [comment]
> > > @i5151 高分屏的话，直接开启Win10的HIDPI兼容即可；适配的还不错。右键点击（或者快捷方式），“属性”→“兼容性”→“更改高DPI设置”，在“替代高DPI缩放设置”上打钩确定就可以了。 @elliottzheng 少侠可以把这个写在说明里。
> > 
> > 
> > 这个从用高分屏之前就知道，效果比原生支持差太多了。
> > 适配高分屏这么难吗？至于用这种方式偷懒？
> 
> 当然很麻烦啊，连网易云音乐和Foxmail都是去年才适配高分屏的，像百度网盘到现在都没适配高分屏；这还是BAT，何况个人开发者啊。

麻烦不是理由，开发不麻烦？

个人开发者很多，像最近经常交流的Listary、Quicker，他们的软件都比CopyTranslator复杂多了，看看他们的适配，非常完美。

既然选择了开发，就不要怕麻烦，有时间能帮助作者想想建设性的意见，而不是挖坑。一个好软件能靠将就产生吗？如果想把CopyTranslator做强做大，真正推广出去，必须把最基本的问题解决了。

**Comment by roison** [comment]
> 如果微软解决好的话，就没有软件会特意适配高分屏了。

不是微软的锅啊，因为之前的软件界面很多都是基于位图开发的；毕竟Windows要保留对老软件的支持啊，不能像苹果一样简单粗暴的直接放弃不支持高分屏的老软件。我觉得至少对于博主这个界面简洁的软件来说，使用HIDPI兼容的效果是没啥问题的（注意你Win10要在1709以上，最好1809）。
还有就是，如果你在日常使用中必须用到处理不了的其他老软件，可以简单的缩放200%或300%，整百缩放只会粗糙不会糊的（win10 1709以上）。

**Comment by roison** [comment]
> > > > @i5151 高分屏的话，直接开启Win10的HIDPI兼容即可；适配的还不错。右键点击（或者快捷方式），“属性”→“兼容性”→“更改高DPI设置”，在“替代高DPI缩放设置”上打钩确定就可以了。 @elliottzheng 少侠可以把这个写在说明里。
> > > 
> > > 
> > > 这个从用高分屏之前就知道，效果比原生支持差太多了。
> > > 适配高分屏这么难吗？至于用这种方式偷懒？
> > 
> > 
> > 当然很麻烦啊，连网易云音乐和Foxmail都是去年才适配高分屏的，像百度网盘到现在都没适配高分屏；这还是BAT，何况个人开发者啊。
> 
> 麻烦不是理由，开发不麻烦？
> 
> 个人开发者很多，像最近经常交流的Listary、Quicker，他们的软件都比CopyTranslator复杂多了，看看他们的适配，非常完美。
> 
> 既然选择了开发，就不要怕麻烦，有时间能帮助作者想想建设性的意见，而不是挖坑。一个好软件能靠将就产生吗？如果想把CopyTranslator做强做大，真正推广出去，必须把最基本的问题解决了。

同学，你也看到我截的图了（4K下175%缩放）；博主这个是只有两个基本文字界面的软件，如果你觉得这个界面仍然不能接受的话我这也没办法了。我是觉得博主开发出这个软件方便大家我们应该感恩才是。提建议当然是应该的，但是建议是建议，不是“要求”，你说是吧?

**Comment by i5151** [comment]
> > 如果微软解决好的话，就没有软件会特意适配高分屏了。
> 
> 不是微软的锅啊，因为之前的软件界面很多都是基于位图开发的；毕竟Windows要保留对老软件的支持啊，不能像苹果一样简单粗暴的直接放弃不支持高分屏的老软件。我觉得至少对于博主这个界面简洁的软件来说，使用HIDPI兼容的效果是没啥问题的（注意你Win10要在1709以上，最好1809）。
> 还有就是，如果你在日常使用中必须用到处理不了的其他老软件，可以简单的缩放200%或300%，整百缩放只会粗糙不会糊的（win10 1709以上）。

不是说是微软的锅，是说微软解决的不好，没有原生的好。

如果CopyTranslator是已经停止开发的老软件，那就算了，肯定不会给作者提这个建议，也根本不会理会这个软件了。

我的系统是正版的Windows 10专业工作版，1809,15.6寸，缩放250%。这么细腻的显示屏看没有适配高分屏的软件的模糊的，稍微看一会儿真的会晕，能用的话，管它适配不适配呢。

**Comment by i5151** [comment]
> > > > > @i5151 高分屏的话，直接开启Win10的HIDPI兼容即可；适配的还不错。右键点击（或者快捷方式），“属性”→“兼容性”→“更改高DPI设置”，在“替代高DPI缩放设置”上打钩确定就可以了。 @elliottzheng 少侠可以把这个写在说明里。
> > > > 
> > > > 
> > > > 这个从用高分屏之前就知道，效果比原生支持差太多了。
> > > > 适配高分屏这么难吗？至于用这种方式偷懒？
> > > 
> > > 
> > > 当然很麻烦啊，连网易云音乐和Foxmail都是去年才适配高分屏的，像百度网盘到现在都没适配高分屏；这还是BAT，何况个人开发者啊。
> > 
> > 
> > 麻烦不是理由，开发不麻烦？
> > 个人开发者很多，像最近经常交流的Listary、Quicker，他们的软件都比CopyTranslator复杂多了，看看他们的适配，非常完美。
> > 既然选择了开发，就不要怕麻烦，有时间能帮助作者想想建设性的意见，而不是挖坑。一个好软件能靠将就产生吗？如果想把CopyTranslator做强做大，真正推广出去，必须把最基本的问题解决了。
> 
> 同学，你也看到我截的图了（4K下175%缩放）；博主这个是只有两个基本文字界面的软件，如果你觉得这个界面仍然不能接受的话我这也没办法了。我是觉得博主开发出这个软件方便大家我们应该感恩才是。提建议当然是应该的，但是建议是建议，不是“要求”，你说是吧?

小同学，你的4k不细腻的屏能看，不代表别人的屏也能看，你能将就不代表别人也能将就。作者开发这个软件，能对我产生帮助，我肯定是感谢他的，收费的话，很可能会买，不收费额可能捐助。但不管是什么目的，既然开发就要做好，只是糊弄玩玩，还不如不开放呢。我提建议也是为了这个软件好，也是想让它变得更好，否则，谁有闲工夫管它。

我不知道你是在几年级的时候把建议和要求混为一谈的，那你说说，你给我提的是建议还是要求？

**Comment by roison** [comment]
> > > 如果微软解决好的话，就没有软件会特意适配高分屏了。
> > 
> > 
> > 不是微软的锅啊，因为之前的软件界面很多都是基于位图开发的；毕竟Windows要保留对老软件的支持啊，不能像苹果一样简单粗暴的直接放弃不支持高分屏的老软件。我觉得至少对于博主这个界面简洁的软件来说，使用HIDPI兼容的效果是没啥问题的（注意你Win10要在1709以上，最好1809）。
> > 还有就是，如果你在日常使用中必须用到处理不了的其他老软件，可以简单的缩放200%或300%，整百缩放只会粗糙不会糊的（win10 1709以上）。
> 
> 不是说是微软的锅，是说微软解决的不好，没有原生的好。
> 
> 如果CopyTranslator是已经停止开发的老软件，那就算了，肯定不会给作者提这个建议，也根本不会理会这个软件了。
> 
> 我的系统是正版的Windows 10专业工作版，1809,15.6寸，缩放250%。这么细腻的显示屏看没有适配高分屏的软件的模糊的，稍微看一会儿真的会晕，能用的话，管它适配不适配呢。

我现在缩放到250%，然后用你刚才比较的方式比较下适配于否，你看看文章效果有明显差别么?

![2019-01-10 130929](https://user-images.githubusercontent.com/33749821/50947397-18520d00-14d9-11e9-8d7d-dea4100283fc.png)

**Comment by elliottzheng** [comment]
@i5151 @roison 两位，不必争论了，如果大家一致认为使用chrome在高分屏下浏览网页不存在这种问题的话，那么这个问题在下一个版本就不会出现，因为下一个版本将是基于electron构建，他本质是也是使用chroium内核进行渲染的。

**Comment by i5151** [comment]
> > > > 如果微软解决好的话，就没有软件会特意适配高分屏了。
> > > 
> > > 
> > > 不是微软的锅啊，因为之前的软件界面很多都是基于位图开发的；毕竟Windows要保留对老软件的支持啊，不能像苹果一样简单粗暴的直接放弃不支持高分屏的老软件。我觉得至少对于博主这个界面简洁的软件来说，使用HIDPI兼容的效果是没啥问题的（注意你Win10要在1709以上，最好1809）。
> > > 还有就是，如果你在日常使用中必须用到处理不了的其他老软件，可以简单的缩放200%或300%，整百缩放只会粗糙不会糊的（win10 1709以上）。
> > 
> > 
> > 不是说是微软的锅，是说微软解决的不好，没有原生的好。
> > 如果CopyTranslator是已经停止开发的老软件，那就算了，肯定不会给作者提这个建议，也根本不会理会这个软件了。
> > 我的系统是正版的Windows 10专业工作版，1809,15.6寸，缩放250%。这么细腻的显示屏看没有适配高分屏的软件的模糊的，稍微看一会儿真的会晕，能用的话，管它适配不适配呢。
> 
> 我现在缩放到250%，然后用你刚才比较的方式比较下适配于否，你看看文章效果有明显差别么?
> 
> ![2019-01-10 130929](https://user-images.githubusercontent.com/33749821/50947397-18520d00-14d9-11e9-8d7d-dea4100283fc.png)

不用点开，就相当明显的差别。

**Comment by i5151** [comment]
> @i5151 @roison 两位，不必争论了，如果大家一致认为使用chrome在高分屏下浏览网页不存在这种问题的话，那么这个问题在下一个版本就不会出现，因为下一个版本将是基于electron构建，他本质是也是使用chroium内核进行渲染的。

这是解决之道👍

**Comment by roison** [comment]
> @i5151 @roison 两位，不必争论了，如果大家一致认为使用chrome在高分屏下浏览网页不存在这种问题的话，那么这个问题在下一个版本就不会出现，因为下一个版本将是基于electron构建，他本质是也是使用chroium内核进行渲染的。

Cool
