### ISSUE TITLE
检测到复制操作之后，显示窗口是否可以置于最上层？自动置顶和置低是否可以实现？

### ISSUE THREAD

**Issue by ChacesXia** [elliottzheng/CopyTranslator#20]
前言：
请先查看wiki中的`使用指南`以及`下一步计划`，**您想要的特性可能已经被实现/已经在计划中**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完`使用指南`以及`下一步计划`，确定该特性未被实现/未计划实现。欢迎继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
简明扼要地描述了问题所在。

**描述您想要的解决方案**
简明扼要地描述您想要发生的事情。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。

**附加背景**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by elliottzheng** [comment]
Duplicate of #15
