### ISSUE TITLE
请问下个版本能增加Mac版本支持吗？

### ISSUE THREAD

**Issue by l6270789** [elliottzheng/CopyTranslator#22]
感谢开发这么好的软件！请问下个版本能增加Mac版本支持吗？

**Comment by elliottzheng** [comment]
感谢支持，已经在计划中了，详情可以看issue #21 重复

**Comment by elliottzheng** [comment]
@l6270789 可以试下[Pre-Release](https://github.com/CopyTranslator/CopyTranslator/releases/tag/0.0.8-alpha-win)

**Comment by l6270789** [comment]
![image](https://user-images.githubusercontent.com/20334795/54172800-4d1f1800-44ba-11e9-85df-94857b42b82f.png)

顶栏显示有点问题，然后软件启动时系统会卡顿，还望完善！感谢！
