### ISSUE TITLE
复制文本后自动弹出翻译的结果

### ISSUE THREAD

**Issue by BigBigWolf-AI** [elliottzheng/CopyTranslator#27]
前言：
请务必先查看项目的[project](https://github.com/elliottzheng/CopyTranslator/projects)，这里列出了CopyTranslator之后将会实现的特性，**您想要的特性有很大的可能已经被实现/已经在计划中**，CopyTranslator经过多次迭代，功能越来越丰富（~~复杂~~），不阅读完整使用指南无法完全发挥其功能，如果您阅读完Project，确定该特性未被实现/未计划实现。非常欢迎您继续下面的工作提出增加新特性的请求。

**您的功能请求是否与问题有关？请描述一下.**
用adobe acrobat pro打开一个PDF文档，然后复制一段英文，软件会自动翻译，但是并没有自动弹出显示翻译结果，需要手动选中该软件才能查看翻译结果。选择自动显示，在专注模式下也不能实现自动显示。

**描述您想要的解决方案**
复制后自动弹出翻译结果。无论时在专注模式还是在对照模式

**描述您考虑过的替代方案**
无

**附加背景**
无

**Comment by elliottzheng** [comment]
您好，您的描述非常模糊，我看不懂您说的是什么意思。您需要补充一些细节。
自动显示是指软件在贴边隐藏后，当检测到剪贴板变化， 会自动显示出来。但是在没有始终置顶的情况下，您可能看不见他的结果框。
而且暂时现在，自动显示和贴边隐藏都只支持专注模式。

**Comment by elliottzheng** [comment]
您所提的所谓“自动显示“”可能是指 #15 中提到的“自动置顶“

**Comment by BigBigWolf-AI** [comment]
对的，就是自动置顶，刚明白怎么用，谢谢，你的软件超级nice，期待Linux和mac平台

**Comment by elliottzheng** [comment]
谢谢支持
