### ISSUE TITLE
快捷键允许自定义

### ISSUE THREAD

**Issue by pjgao** [elliottzheng/CopyTranslator#28]
**您的功能请求是否与问题有关？请描述一下.**
当前在专注模式调整字体大小时，使用shift + F3和shift + F4缩小或增大专注模式的字体大小。我这边出现的问题是按下了shift+f4后，按shift+f3无法再缩小。估计是由于存在热键冲突，(snipaste的隐藏全部贴图键默认为shift+F3)，关闭了snipaste后这个问题仍然无法解决。目前我的专注模式已不可正常使用(字体不小心放大到了最大却无法缩小回来)。

**描述您想要的解决方案**
将字体切换键换成chrome兼容的ctrl + -，或者在设置中提供自定义快捷键选项。

**描述您考虑过的替代方案**
ctrl+滚轮（不过我平时只用键盘手头无鼠标未测试）

**附加背景**
![image](https://user-images.githubusercontent.com/22350313/51110447-a9a3e500-1833-11e9-9cfb-663ad09d678c.png)

**Comment by elliottzheng** [comment]
您好，快捷键的自定义，以及字体大小的直接设置，将在下一版本加入。
对于您现在的情况，您可以删除用户目录下的copytranslator.json文件来重置所有设置，即
`c:\users\您的用户名\copytranslator.json`

**Comment by pjgao** [comment]
经测试，修改了snipaste的快捷键并重启snipaste后，该快捷键可以正常使用了。
多谢您的优秀的工作！期待下一个版本。
