### ISSUE TITLE
Problems with system compatibility

### ISSUE THREAD

**Issue by elliottzheng** [elliottzheng/CopyTranslator#3]

**Comment by bjwanghao** [comment]
win10 64位系统  打开提示 Failed to execute script CopyTranslator

**Comment by elliottzheng** [comment]
> win10 64位系统 打开提示 Failed to execute script CopyTranslator

建议你新开一个issue吧，这个issue是用来反馈增强的建议的。此外，你所使用的版本是？

**Comment by bjwanghao** [comment]
5.03可以打开  6.0就这问题

**Comment by elliottzheng** [comment]
@bjwanghao 
我这边也是win10,64位测试没有问题，重新打包了一个preview，你试下可不可以吧，如果不行的话，可能你只能暂时先使用0.0.5.3 
[https://pan.baidu.com/s/1EuHMi1dLjpIvCGdAQS2r1w](https://pan.baidu.com/s/1EuHMi1dLjpIvCGdAQS2r1w)

**Comment by elliottzheng** [comment]
不太清楚，系统内部的事情太复杂了，我这里已经尽量打包了所需要的库，照理说不应该出现这种问题。

**Comment by mayunbaba2** [comment]
支持字幕文件（SRT ASS/SSA)翻译吗

**Comment by elliottzheng** [comment]
@mayunbaba2 字幕文件翻译的话，[https://github.com/1c7/translate-subtitle-file](https://github.com/1c7/translate-subtitle-file)了解一下

**Comment by elliottzheng** [comment]
@bjwanghao 发布的蓝奏云那边构建了个32位的版本，你可以试下可不可以
