### ISSUE TITLE
[Features]请问开发者能否接入彩云小译的API

### ISSUE THREAD

**Issue by Memorainer** [elliottzheng/CopyTranslator#37]
随便Copy了一段文字，用彩云小译的Chrome插件在线翻译跟开发者您的CopyTranslator对比了一下，感觉小译在自然语义的处理上更加接近“人类”。阅读理解习惯上也更加符合自然语言的表达习惯。
对程序开发不是很懂，但小译貌似是提供API的，开发者是不是可以整合到CopyTranslator中，提高程序的翻译水准。小译的在线翻译确实做得很好，但是比较尴尬的是并没有提供桌面端的程序。如果能整合当然是非常棒的了。不清楚难度几何，仅作为建议在此提出。
感谢！
![snipaste_2019-01-25_22-12-57](https://user-images.githubusercontent.com/17745131/51751429-ce2f7500-20ef-11e9-9c9e-717b0e3837f9.png)

**Comment by elliottzheng** [comment]
您好，仅从实现的角度，这是不难的，但是彩云小译提供的api是收费的，每月免费额度有限，如果我申请TOKEN， 以copytranslator当前的使用人数来估计，这一下子就没了。如果让大家自己去申请TOKEN的话，他这个申请方式又很复杂，并不容易。
我会考虑实现，但是这项需求的优先级会非常低，当前的精力主要是要改善其他的翻译体验，还请见谅。
![default](https://user-images.githubusercontent.com/22427645/51781102-52651500-214f-11e9-9207-cd3f25e25c83.png)
