### ISSUE TITLE
请问是不是不支持winxp

### ISSUE THREAD

**Issue by chenfengrugao** [elliottzheng/CopyTranslator#38]
**描述问题**
我的电脑是winxp，安装有python3.4。下载https://github.com/elliottzheng/CopyTranslator/releases/download/v0.0.7-RC1/CopyTranslator_v0.0.7-Kylin-RC1.zip，解压，然后双击CopyTranslator.exe没有任何反应。所以只是想问一下，是不是不支持winxp，谢谢！

**Comment by elliottzheng** [comment]
您好，很抱歉，当前版本的CopyTranslator没有在xp上测试过，后续版本由于所用框架Electron本身只支持win7以上，个人去做适配xp非常困难，精力有限，还请见谅

**Comment by elliottzheng** [comment]
不过，如果后续我能获得[https://github.com/jetiny/electron-xp](https://github.com/jetiny/electron-xp)这个授权的话，也许可以支持xp
