### ISSUE TITLE
[Features]请求增加TranslateBulker接口，添加整书/整篇论文翻译模式，以及在对照模式中增加复制原文功能

### ISSUE THREAD

**Issue by ainsel1729** [elliottzheng/CopyTranslator#39]
**您的功能请求是否与问题有关？请描述一下.**
1.使用CopyTranslator翻译超出5000字符文章（即谷歌翻译一次翻译限度）时，响应时间极长，无结果。
2.在对照模式中无复制原文（删除异常换行后的原文）选项

**描述您想要的解决方案**
增加全文翻译模式，允许使用者复制整篇pdf一键翻译，引入TranslateBulker接口，等待适量时间后得到全篇pdf翻译结果
TranslateBulker说明文档与下载地址： http://piaoyi.org/seotool/TranslateBulker-Google.html
**描述您考虑过的替代方案**
上传pdf文件，直接从pdf导出全文TXT,用CopyTranlator删除多余换行，再导入TranslateBulker接口（TranslateBulker的文件导入模式仅接受.txt,.htm.html三种格式导入），并将输出结果导出成全文txt

**附加背景**
我现在采取的解决方案是：从英文论文pdf中全选并复制文章，在对照模式中看到原文段落多余换行已消除后（因全选文章或书籍较长，消除换行往往需要等待1-5s），切换到专注模式（此时可见区域为空白），右键选择复制原文。将原文复制进TranslateBulker，点选翻译，得到长篇翻译结果。

原文过长，自动删除换行，但无翻译：
![image](https://user-images.githubusercontent.com/42263693/51883452-dcb2b080-23bd-11e9-8025-0e7c14b11faf.png)
专注模式下无文章，但可右键选择复制原文
![image](https://user-images.githubusercontent.com/42263693/51883415-bbea5b00-23bd-11e9-9200-e6507b1f98c7.png)
将原文导入TranslateBulker并翻译
![image](https://user-images.githubusercontent.com/42263693/51883016-1aaed500-23bc-11e9-8b16-137fa2199ead.png)

TranslateBulker为免费软件，并且同样使用google翻译，接入应该不难
可能存在缺陷：TranslateBulker要求 Microsoft's .NET 3.5或以上版本

**Comment by elliottzheng** [comment]
你好，我会加一个**复制去除换行后的文本的按钮**，但是不会添加这个TranslateBulker接口。
CopyTranslator是用来辅助阅读和翻译的，并不适合用于全文翻译，全文翻译建议直接到各大提供pdf翻译的网页翻译使用。
