### ISSUE TITLE
在专注模式下也无法用shift+F3或F4调节字体大小

### ISSUE THREAD

**Issue by hua70720219** [elliottzheng/CopyTranslator#40]
**描述问题**

在专注模式和对照下都无法用shift+F3或F4调节字体大小，专注模式下用shift+鼠标滚轮能临时调节字体大小。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v0.0.6.1 x86 版
 - 出现问题时的模式：照模式和专注模式
 - 操作系统：win10 64位
 - 阅读器：福昕阅读器，官网下载
 - 出现问题的文档：
 - 出现问题的段落：

**如何复现这个问题**
重现行为的步骤：
1. 
2. 
3. 
4. 

**问题出现时，当时的CopyTranslator的设置截图**

请截取主模式窗口

**是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？**

没有在其他·阅读器试过
**之前的版本有出现这种问题吗？如果没有出现的话，请提供一个已知无该bug的版本号**

**Comment by elliottzheng** [comment]
您好，请查看issue #28 ，这个issue可能与您遇到的问题相关，如果有冲突的热键的话，可能无法使用shift+f3/4进行缩放，下个版本会提供热键自定义

**Comment by hua70720219** [comment]
感谢你的回复

**Comment by elliottzheng** [comment]
新版本如无意外将会使用ctrl+wheel进行缩放
