### ISSUE TITLE
PDF文档翻译问题

### ISSUE THREAD

**Issue by wang08270** [elliottzheng/CopyTranslator#5]
使用的是福昕PDF阅读器，如果直接复制内容不能出现翻译结果。
在SWITCH MODE 中才出现的问题。

**Comment by elliottzheng** [comment]
您好，我需要更多的细节。请详细描述所使用的CopyTranslator版本号以及构建版本（x86，x64），当时的设置（可以直接截图），所使用的windows系统，以及问题出现的段落，复制的方法，最好能附上文档，阅读器的下载地址。另外，是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？

**Comment by wang08270** [comment]
> 您好，我需要更多的细节。请详细描述所使用的CopyTranslator版本号以及构建版本（x86，x64），当时的设置（可以直接截图），所使用的windows系统，以及问题出现的段落，复制的方法，最好能附上文档，阅读器的下载地址。另外，是只在这个阅读器上不能使用，还是在浏览器及其他的阅读器也不可以使用？

谢谢，我使用的是最新的版本，WIN7系统，另外经过你的提醒，我发现在谷歌阅读器上使用正常，是否同该版本的阅读器有关？

**Comment by wang08270** [comment]
![image](https://user-images.githubusercontent.com/31719247/46593853-c2e51900-cb01-11e8-92f8-9413faaa6cdd.png)

**Comment by wang08270** [comment]
![image](https://user-images.githubusercontent.com/31719247/46593893-03dd2d80-cb02-11e8-846f-35f12f5cc5ff.png)

**Comment by elliottzheng** [comment]
感谢您补充了细节，我在0.0.6.1中成功复现了您的问题，经过测试在0.0.6.2_preview 没有这个问题，您可以先尝试一下最新构建的v0.0.6.2_preview。[https://www.lanzous.com/b389682/](https://www.lanzous.com/b389682/)，另外建议不要打开自动检测语言，0.0.6.1的智能互译会导致翻译的逻辑较为混乱，这点在0.0.6.2preview中已经得到改善。

**Comment by elliottzheng** [comment]
这个问题可能是复制和黏贴机制的问题，0.0.6.1采用了和0.0.6.2_preview，0.0.5.3不同的复制和黏贴机制，这两种机制各有好处,也都有已知的问题，后续会考虑如何改进

**Comment by wang08270** [comment]
好的，感谢！
