### ISSUE TITLE
为什么win10会报毒

### ISSUE THREAD

**Issue by supercaizehua** [elliottzheng/CopyTranslator#8]

**Comment by elliottzheng** [comment]
软件是用pyinstaller打包的，全部代码，包括打包的代码都是开源的， 为什么报毒我不知道，我也很迷惑，但是只要是通过我提供的下载方式的下载的（其他渠道不保证），请放心使用。

**Comment by elliottzheng** [comment]
另外，还请按照issue模板提问，不规范的提问将使工作变得低效，比如我不知道你到底是使用的哪个版本的CopyTranslator，是哪个软件报毒，报毒是报的什么毒，哪个文件报毒等等，谢谢合作。感谢您的建议。

**Comment by supercaizehua** [comment]
**描述问题**
https://www.lanzous.com/b389682/
在蓝奏云下载的preview版本win10安全中心报毒，我让同学在其电脑上下载，360安全卫士报毒，所有报毒的情况都是连压缩包都没有解压开就报毒了，然后我加入白名单后，可以正常使用，但是似乎使用过程中，会有几个变种，分别是Tiggre!plock Tiggre!rfn等等，我没有详细的试到底有多少变种。详情看截图。

**系统环境（请填写以下信息）：**
 - CopyTranslator版本：如v0.0.6.2 preview 版
 - 操作系统：如win10 64位

**如何复现这个问题**
重现行为的步骤：
1. 从蓝奏云下载文件
2. 等杀毒软件报毒


![copytranslator](https://user-images.githubusercontent.com/33114810/49085352-cdfc3000-f28c-11e8-9a72-edfc2ca56446.png)
![copy 2](https://user-images.githubusercontent.com/33114810/49085421-ef5d1c00-f28c-11e8-8634-b9485c4af3a0.png)
![copy 3](https://user-images.githubusercontent.com/33114810/49085433-f5eb9380-f28c-11e8-87fc-9605b2b717e4.png)
![copy 4](https://user-images.githubusercontent.com/33114810/49085446-ff74fb80-f28c-11e8-8492-ddc69270714c.png)
![copy 6](https://user-images.githubusercontent.com/33114810/49085513-25020500-f28d-11e8-8aab-1270fa9a4317.png)

**Comment by elliottzheng** [comment]
非常感谢您的反馈，我这里也发生了这样的情况，原因不明，我后续可能会提交软件给这些杀软检测，同时发布前会经过杀毒软件检测，并在发布后同时提供MD5验证，以保证发布的软件不会被恶意篡改。
![image](https://user-images.githubusercontent.com/22427645/49085924-2da70b00-f28e-11e8-924b-30720c84f004.png)
作为开发人员，我们习惯了杀毒软件误报，一般是不影响使用的，不过还是长个心眼，因为可能放到云盘的东西会被篡改也说不定。所以可能从github下载的会是比较可信的。

我测试最新v0.0.7.0的alpha构建版本时没有发现这个问题，您可以下载下面的文件看下是否会出现同样的问题。v0.0.7.0正式版将在本周内发布，敬请期待。[CopyTranslator_v0.0.7.0_alpha_11_25.zip](https://github.com/elliottzheng/CopyTranslator/files/2620254/CopyTranslator_v0.0.7.0_alpha_11_25.zip)

**Comment by supercaizehua** [comment]
![image](https://user-images.githubusercontent.com/33114810/49087277-888e3180-f291-11e8-8021-9eb896e63724.png)
这个alpha版本没有报毒了，但是在我这里打不开

**Comment by elliottzheng** [comment]
哦哦，忘记提醒你了，如果之前按过旧版的，需要删除 c://users/你的用户名/copytranslator.json这个文件

**Comment by supercaizehua** [comment]
搞定了，能用，没有报毒，新版本终于可以调整主模式的长度了

**Comment by elliottzheng** [comment]
alpha还有些小bug，正式版会改善，还请多多安利哦😄
